from fastapi import APIRouter
from app.api.routes import auth, clients, services, companies, admin, billing, agents, plans, diagnostics, requests, users, finance, roles, suppliers, purchases, documents, assignments

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(clients.router, prefix="/clients", tags=["clients"])
api_router.include_router(services.router, prefix="/services", tags=["services"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(billing.router, prefix="/billing", tags=["billing"])
api_router.include_router(agents.router, prefix="/agents", tags=["agents"])
api_router.include_router(plans.router, prefix="/plans", tags=["plans"])
api_router.include_router(diagnostics.router, prefix="/diagnostics", tags=["diagnostics"])
api_router.include_router(requests.router, prefix="/requests", tags=["requests"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(finance.router, prefix="/finance", tags=["finance"])
api_router.include_router(roles.router, prefix="/roles", tags=["roles"])
api_router.include_router(suppliers.router, prefix="/suppliers", tags=["suppliers"])
api_router.include_router(purchases.router, prefix="/purchases", tags=["purchases"])
api_router.include_router(documents.router, prefix="/documents", tags=["documents"])
api_router.include_router(assignments.router, prefix="/assignments", tags=["assignments"])
