"""add_diagnostic_and_lead_models

Revision ID: 6aa3493ea73c
Revises: 0c83f4ff4e75
Create Date: 2026-03-19 14:27:22.492171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa3493ea73c'
down_revision: Union[str, Sequence[str], None] = '0c83f4ff4e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosticos_empresariais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('nome_responsavel', sa.String(), nullable=True),
    sa.Column('quantidade_colaboradores', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('atendimento_score', sa.Integer(), nullable=False),
    sa.Column('comunicacao_score', sa.Integer(), nullable=False),
    sa.Column('processos_score', sa.Integer(), nullable=False),
    sa.Column('marketing_score', sa.Integer(), nullable=False),
    sa.Column('produtividade_score', sa.Integer(), nullable=False),
    sa.Column('tecnologia_score', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('classificacao', sa.String(), nullable=False),
    sa.Column('gargalo_critico', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_empresa', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    op.drop_table('diagnosticos_empresariais')
    # ### end Alembic commands ###
