"""add_sales_module

Revision ID: c9fabf74d8c4
Revises: f67b9c3e8d31
Create Date: 2026-03-19 20:22:28.888485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9fabf74d8c4'
down_revision: Union[str, Sequence[str], None] = 'f67b9c3e8d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_funnel_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_funnel_stages_company_id'), 'sales_funnel_stages', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_funnel_stages_id'), 'sales_funnel_stages', ['id'], unique=False)
    op.create_table('sales_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_goals_company_id'), 'sales_goals', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_goals_id'), 'sales_goals', ['id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_company_id'), 'sales', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.add_column('leads', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('stage_id', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_foreign_key(None, 'leads', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'leads', 'sales_funnel_stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_column('leads', 'status')
    op.drop_column('leads', 'stage_id')
    op.drop_column('leads', 'company_id')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_company_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_sales_goals_id'), table_name='sales_goals')
    op.drop_index(op.f('ix_sales_goals_company_id'), table_name='sales_goals')
    op.drop_table('sales_goals')
    op.drop_index(op.f('ix_sales_funnel_stages_id'), table_name='sales_funnel_stages')
    op.drop_index(op.f('ix_sales_funnel_stages_company_id'), table_name='sales_funnel_stages')
    op.drop_table('sales_funnel_stages')
    # ### end Alembic commands ###
