"""add ice fields to tasks

Revision ID: e68a9498493c
Revises: 7a7d093e869a
Create Date: 2026-03-19 19:50:18.842084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68a9498493c'
down_revision: Union[str, Sequence[str], None] = '7a7d093e869a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('impact', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('confidence', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('effort', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('ice_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ice_score')
    op.drop_column('tasks', 'effort')
    op.drop_column('tasks', 'confidence')
    op.drop_column('tasks', 'impact')
    # ### end Alembic commands ###
