"""Add modules to company

Revision ID: 3c9d8db56ee6
Revises: 62b26728a55c
Create Date: 2026-03-20 19:14:39.208249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c9d8db56ee6'
down_revision: Union[str, Sequence[str], None] = '62b26728a55c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('modules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'modules')
    # ### end Alembic commands ###
