"""Add document and phone to company

Revision ID: 62b26728a55c
Revises: c9fabf74d8c4
Create Date: 2026-03-20 18:45:47.329286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b26728a55c'
down_revision: Union[str, Sequence[str], None] = 'c9fabf74d8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('document', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(), nullable=True))
    op.create_index(op.f('ix_companies_document'), 'companies', ['document'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_document'), table_name='companies')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'document_type')
    op.drop_column('companies', 'document')
    # ### end Alembic commands ###
