"""add support requests table

Revision ID: f67b9c3e8d31
Revises: e68a9498493c
Create Date: 2026-03-19 20:12:19.523447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67b9c3e8d31'
down_revision: Union[str, Sequence[str], None] = 'e68a9498493c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('responsible_id', sa.UUID(), nullable=False),
    sa.Column('solicitation', sa.String(), nullable=False),
    sa.Column('gravity', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('tendency', sa.Integer(), nullable=True),
    sa.Column('gut_score', sa.Integer(), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_requests_company_id'), 'support_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_support_requests_id'), 'support_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_requests_id'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_company_id'), table_name='support_requests')
    op.drop_table('support_requests')
    # ### end Alembic commands ###
